version: "3"

services:

  postgres:
    image: postgres:16.0-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123

  allocation:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ..:/code
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    network_mode: service:postgres
    tty: true
    command: /bin/bash

volumes:
  postgres-data:
